config/routes.rb
Rails.application.routes.draw do
  root "warehouses#index"

  resources :inventory_items
  resources :warehouses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  # Associations
  belongs_to :warehouse, inverse_of: :inventory_items

  # Callbacks
  before_update :update_warehouse_stocks, if: :warehouse_changed?
  after_create :increase_warehouse_stocks
  after_destroy :delete_warehouse_stocks

  # Validations
  validates_presence_of :quantity, :status, :item_code
  validates_uniqueness_of :item_code

  validates :price, :presence => true,
            :numericality => true

  validates :price_per_unit, 
            :numericality => true,
            :allow_nil => true

  scope :in_warehouse, ->(warehouse_id) { where(warehouse_id: warehouse_id) if warehouse_id.present? }

  def update_warehouse_stocks
    Warehouse.find_by(id: warehouse_id_was)&.decrement!(:total_stock)
    warehouse&.increment!(:total_stock)
  end

  def increase_warehouse_stocks
    warehouse.increment!(:total_stock)
  end

  def delete_warehouse_stocks
    warehouse.decrement!(:total_stock)
  end

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  # Associations
  has_many :inventory_items, inverse_of: :warehouse, dependent: :destroy

  # Validations
  validates_presence_of :address, :city, :zipcode

  validates :contact_number, :presence => true,
                    :numericality => true,
                    :length => { :minimum => 10, :maximum => 15 }

  validates :zipcode, length: { is: 6 }


  def info
    [address, city, zipcode].join(",")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: %i[ show edit update destroy ]

  # GET /inventory_items
  def index
    @inventory_items = InventoryItem.in_warehouse(filter_params[:warehouse_id])
  end

  # GET /inventory_items/1
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new(warehouse_id: filter_params[:warehouse_id])
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to inventory_item_url(@inventory_item), notice: I18n.t('inventory_items.successfully_created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to inventory_item_url(@inventory_item), notice: I18n.t('inventory_items.successfully_updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  def destroy
    @inventory_item.destroy

    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: I18n.t('inventory_items.successfully_destroyed') }
    end
  end

  private

    def filter_params
      params.permit(:warehouse_id)
    end

    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    def inventory_item_params
      params.require(:inventory_item).permit(:warehouse_id, :status, :item_code, :price, :price_per_unit, :quantity, :weight)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  def show
    @warehouse_inventory = @warehouse.inventory_items
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: I18n.t('warehouse.successfully_created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: I18n.t('warehouse.successfully_updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: I18n.t('warehouse.successfully_destroyed') }
    end
  end

  private

    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    def warehouse_params
      params.require(:warehouse).permit(:city, :zipcode, :address, :contact_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper

  def warehouses_for_select
    Warehouse.all.collect do |warehouse| 
      ["#{warehouse.info}", warehouse.id]
    end
  end

end

app/views/inventory_items/_form.html.erb
<%= form_with(model: inventory_item) do |form| %>
  <% if inventory_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_item.errors.count, "error") %> prohibited this Inventory item from being saved:</h2>

      <ul>
        <% inventory_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="overflow-x:auto;">
    <table>
      <tr>
        <th><%= form.label :warehouse_id, style: "display: block" %></th>
        <td><%= form.select(:warehouse_id, warehouses_for_select, :prompt => 'Select') %></td>
      </tr>
      <tr>
        <th><%= form.label :status, style: "display: block" %></th>
        <td>
          <%= form.select :status, options_for_select(INVENTORY_STATUSES) %>
        </td>
      </tr>
      <tr>
        <th><%= form.label :item_code, style: "display: block" %></th>
        <td><%= form.text_field :item_code %></td>
      </tr>
      <tr>
        <th><%= form.label :price, style: "display: block" %></th>
        <td><%= form.text_field :price %></td>
      </tr>
      <tr>
        <th><%= form.label :price_per_unit, style: "display: block" %></th>
        <td><%= form.text_field :price_per_unit %></td>
      </tr>
      <tr>
        <th><%= form.label :quantity, style: "display: block" %></th>
        <td><%= form.number_field :quantity %></td>
      </tr>
      <tr>
        <th><%= form.label :weight, style: "display: block" %></th>
        <td><%= form.number_field :weight %></td>
      </tr>
    </table>
  </div>
  <div class="submit_button">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_items/_list.html.erb
<%- if inventory_items.blank? %>
  <p style="text-align: center">
    No Inventory Items Found, Create one
  </p>
<% else %>
  <div style="overflow-x:auto;">
    <table>
      <tr>
        <th>Status</th>
        <th>Item code</th>
        <th>Price</th>
        <th>Price per unit</th>
        <th>Quantity</th>
        <th>Weight</th>
        <th colspan=3 style="text-align: center">Actions</th>
      </tr>
      <% inventory_items.each do |inventory_item| %>
        <tr>
          <td><%= inventory_item.status %></td>
          <td><%= inventory_item.item_code %></td>
          <td><%= inventory_item.price %></td>
          <td><%= inventory_item.price_per_unit %></td>
          <td><%= inventory_item.quantity %></td>
          <td><%= inventory_item.weight %></td>
          <td><%= link_to 'Show', inventory_item %></td>
          <td><%= link_to 'Edit', edit_inventory_item_path(inventory_item) %></td>
          <td><%= button_to 'Delete', inventory_item, method: :delete, class: 'delete_button' %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Editing Inventory Item</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= inventory_items_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <%= link_to @inventory_item do %>
        <img src=<%= asset_path("eye.png") %> alt="Logo" width="40" />
      <% end %>
    </div>
  </div>

  <%= render "form", inventory_item: @inventory_item %>
  
</div>

app/views/inventory_items/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>


  <div class="content" style="display: flex;flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Inventory items</h1>
    </div>
    <div class="custom_actions">
      <a href=<%= new_inventory_item_path(warehouse_id: params[:warehouse_id]) %> ><img src=<%= asset_path("add.png") %> alt="Logo" width="50"></a>
    </div>
  </div>


  <%= render partial: "list", locals: {inventory_items: @inventory_items}%>

  
</div>

app/views/inventory_items/new.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>New Inventory Item</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= inventory_items_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
  </div>

  <%= render "form", inventory_item: @inventory_item %>
  
</div>

app/views/inventory_items/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Inventory Item Info</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= inventory_items_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <a href=<%= edit_inventory_item_path(@inventory_item) %> ><img src=<%= asset_path("edit.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <%= button_to @inventory_item, method: :delete, class: "delete_button" do %>
        <img src=<%= asset_path("delete.png") %> alt="Logo" width="40">
      <% end %>
    </div>
  </div>


  <div style="overflow-x:auto;">
    <table>
      <tr>
        <th>Warehouse</th>
        <td><%= link_to @inventory_item.warehouse.info, @inventory_item.warehouse %></td>
      </tr>
      <tr>
        <th>Status</th>
        <td><%= @inventory_item.status %></td>
      </tr>
      <tr>
        <th>Item code</th>
        <td><%= @inventory_item.item_code %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= @inventory_item.price %></td>
      </tr>
      <tr>
        <th>Price per unit</th>
        <td><%= @inventory_item.price_per_unit %></td>
      </tr>
      <tr>
        <th>Quantity</th>
        <td><%= @inventory_item.quantity %></td>
      </tr>
      <tr>
        <th>Weight</th>
        <td><%= @inventory_item.weight %></td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DhimanLogistics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div id="wrapper">
  <nav role="navigation">
    <header role="banner">
      <a href="/"><img src=<%= asset_path("dhiman-logistics-logo.png") %> alt="Logo" width="50"></a>
      <%# <a>Dhiman Logistics</a> %>
    </header>
    <ul>
      <li><%= link_to "Warehouses", warehouses_path %></li>
      <li><%= link_to "Inventory Items", inventory_items_path %></li>
    </ul>
  </nav>
</div>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div style="overflow-x:auto;">
    <table>
      <tr>
        <th><%= form.label :address, style: "display: block" %></th>
        <td><%= form.text_area :address %></td>
      </tr>
      <tr>
        <th><%= form.label :city, style: "display: block" %></th>
        <td>
          <%= form.select :city, options_for_select(CITIES) %>
        </td>
      </tr>
      <tr>
        <th><%= form.label :zipcode, style: "display: block" %></th>
        <td><%= form.text_field :zipcode %></td>
      </tr>
      <tr>
        <th><%= form.label :contact_number, style: "display: block" %></th>
        <td><%= form.text_field :contact_number %></td>
      </tr>
    </table>
  </div>
  <div class="submit_button">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/_list.html.erb
<%- if warehouses.blank? %>
  <p style="text-align: center">
    No Warehouses Found, Create one
  </p>
<% else %>
  <div style='overflow-x:auto;'>
  <table>
    <tr>
      <th>Total Stock</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Contact Number</th>
      <th colspan=4 style="text-align: center">Actions</th>
    </tr>
    <% warehouses.each do |warehouse| %>
      <tr>
        <td><%= warehouse.total_stock %></td>
        <td><%= warehouse.city %></td>
        <td><%= warehouse.zipcode %></td>
        <td><%= warehouse.contact_number %></td>
        <td>
          <%= link_to 'Show', warehouse %>
        </td>

        <td>
          <%= link_to 'Edit', edit_warehouse_path(warehouse) %>
        </td>

        <td>
          <%= button_to 'Delete', warehouse, method: :delete, class: 'delete_button' %>
        </td>

        <td>
          <%= link_to 'Inventory', inventory_items_path(warehouse_id: warehouse.id) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/warehouses/edit.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Editing warehouse</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= warehouses_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <%= link_to @warehouse do %>
        <img src=<%= asset_path("eye.png") %> alt="Logo" width="40" />
      <% end %>
    </div>
  </div>

  <%= render "form", warehouse: @warehouse %>
  
</div>

app/views/warehouses/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex;flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Warehouses</h1>
    </div>
    <div class="custom_actions">
      <a href=<%= new_warehouse_path %> ><img src=<%= asset_path("add.png") %> alt="Logo" width="50"></a>
    </div>
  </div>


  
  <%= render partial: "list", locals: {warehouses:  @warehouses}%>

</div>

app/views/warehouses/new.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>New warehouse</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= warehouses_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
  </div>

  <%= render "form", warehouse: @warehouse %>
  
</div>

app/views/warehouses/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="content" style="display: flex; flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Warehouse Info</h1>
    </div>

    <div class="custom_actions">
      <a href=<%= warehouses_path %> ><img src=<%= asset_path("back.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <a href=<%= edit_warehouse_path(@warehouse) %> ><img src=<%= asset_path("edit.png") %> alt="Logo" width="40"></a>
    </div>
    <div class="custom_actions">
      <%= button_to @warehouse, method: :delete, class: "delete_button" do %>
        <img src=<%= asset_path("delete.png") %> alt="Logo" width="40">
      <% end %>
    </div>
  </div>


  <div style="overflow-x:auto;">
    <table>
      <tr>
        <th>Total Stock</th>
        <td><%= @warehouse.total_stock %></td>
      </tr>
      <tr>
        <th>City</th>
        <td><%= @warehouse.city %></td>
      </tr>
      <tr>
        <th>Zipcode</th>
        <td><%= @warehouse.zipcode %></td>
      </tr>
      <tr>
        <th>Contact Number</th>
        <td><%= @warehouse.contact_number %></td>
      </tr>
    </table>
  </div>

  &nbsp

  <div class="content" style="display: flex;flex-wrap: wrap;">
    <div class="content_heading">
      <h1>Warehouse Inventory</h1>
    </div>
    <div class="custom_actions">
      <a href=<%= new_inventory_item_path(warehouse_id: @warehouse.id) %> ><img src=<%= asset_path("add.png") %> alt="Logo" width="40"></a>
    </div>
  </div>


  <%= render partial: "inventory_items/list", locals: {inventory_items: @warehouse_inventory}%>

</div>